object fStinger: TfStinger
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'Stinger'
  ClientHeight = 1080
  ClientWidth = 1920
  Color = clBlack
  DefaultMonitor = dmDesktop
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poDesigned
  TransparentColor = True
  TransparentColorValue = clBlack
  OnClose = FormClose
  OnPaint = FormPaint
  PixelsPerInch = 96
  TextHeight = 13
end
